export const bingoItems = new Map([
    ["3nm", "3nm Process"],
    ["aaa_games", "AAA Games on Mac"],
    ["free_space", "Free Space"],
    ["imac_24", "Refreshed 24\" iMac"],
    ["imac_pro", "New iMac Pro"],
    ["ipad_air", "Refreshed iPad Air"],
    ["ipad_mini", "Refreshed iPad Mini"],
    ["ipad_pro", "Refreshed iPad Pros"],
    ["m3_chip", "M3 Chip"],
    ["m3_promax", "M3 Pro and Max Chips"],
    ["mac_gaming", "Mac Gaming Segment"],
    ["mac_testimonies", "New Mac Testimonies"],
    ["macbook_pro", "Refreshed MacBook Pros"],
    ["mba_13", "Refreshed 13\" Macbook Air"],
    ["mba_15", "Refreshed 15\" Macbook Air"],
    ["mbp_13", "13\" MBP Discontinued"],
    ["meaningless_graph", "Meaningless Graph"],
    ["new_apm", "AirPods Max (2nd Gen)"],
    ["new_display", "New Display"],
    ["raytracing_hardware", "Ray Tracing Hardware"],
    ["underground_lab", "Underground Lab"],
    ["under_60", "Under 60 Minutes"],
    ["vision_pro", "Vision Pro Segment"],
]);
