export const bingoItems: Map<string, string> = new Map([
    ["10_on_demos", "10+ Mins on Demos"],
    ["aaa_games", "AAA Games on Mac"],
    ["apple_park_night", "Apple Park at Night"],
    ["atv_segment", "Apple TV+ Segment"],
    ["carbon_neutral", "Carbon Neutral"],
    ["craig_skits", "Craig Skits"],
    ["deeply_thrilled", "\"Deeply Thrilled\""],
    ["fastest_macs", "\"Our fastest Macs yet\""],
    ["free_space", "Free Space"],
    ["gaming_company", "Feat. Gaming Company"],
    ["gonna_love_it", "You're gonna love it"],
    ["imac_24", "Refreshed 24\" iMac"],
    ["imac_pro", "New iMac Pro"],
    ["ipad_air", "Refreshed iPad Air"],
    ["ipad_mini", "Refreshed iPad Mini"],
    ["ipad_pro", "Refreshed iPad Pros"],
    ["m3_chip", "M3 Chip"],
    ["m3_promax", "M3 Pro and Max Chips"],
    ["mac_gaming", "Mac Gaming Segment"],
    ["mac_sales", "Mac Sales Figures"],
    ["mac_testimonies", "New Mac Testimonies"],
    ["macbook_pro", "Refreshed MacBook Pros"],
    ["mba_13", "Refreshed 13\" Macbook Air"],
    ["mba_15", "Refreshed 15\" Macbook Air"],
    ["mbp_13", "13\" MBP Discontinued"],
    ["mbp_color", "New MBP Color"],
    ["meaningless_graph", "Meaningless Graph"],
    ["new_apm", "AirPods Max (2nd Gen)"],
    ["new_display", "New Display"],
    ["no_imac_colors", "No New iMac Colors"],
    ["price_decrease", "Mac Price Decrease"],
    ["rainbow", "Rainbow Cameo"],
    ["raytracing_hardware", "Ray Tracing Hardware"],
    ["spooky", "Spooky"],
    ["third_party_demo", "Boring 3rd Party Demo"],
    ["transition", "Crazy Transition"],
    ["under_60", "Under 60 Minutes"],
    ["underground_lab", "Underground Lab"],
    ["usbc", "USB-C Accessories"],
    ["vision_pro", "Vision Pro Segment"],
    ["welcome", "\"Welcome to Apple Park!\""]
]);