export const bingoTiles: Map<string, string> = new Map([
    ["10_on_demos", "10+ Mins on Demos"],
    ["256_pro_storage", "256GB Pro Base Storage"],
    ["action_button", "Action Button on All Models"],
    ["ai_health_features", "AI Health Features"],
    ["all_day_battery", '"All-Day Battery"'],
    ["android_mentioned", "Android Mentioned"],
    ["apple_arcade", "Arcade Mention"],
    ["apple_park_night", "Apple Park at Night"],
    ["apple_park_roof", "On Apple Park's Roof"],
    ["apple_watch_lives", "Apple Watch Saves Lives"],
    ["artist_cameo", "Famous Artist Cameo"],
    ["atv_segment", "Apple TV+ Segment"],
    ["aw_new_band", "New Band Mechanism"],
    ["aw_se3", "Apple Watch SE (3rd Gen)"],
    ["aw_x", `It's "Apple Watch X"`],
    ["base_ipad", "Refreshed Base iPad"],
    ["better_water_resistance", "Better Water Resistance"],
    ["blazer", "Wears a Blazer"],
    ["brighter_displays", "Brighter Displays"],
    ["carbon_neutral", "Carbon Neutral"],
    ["carplay_mentioned", "CarPlay Mentioned"],
    ["craig_skits", "Craig Skits"],
    ["deeply_thrilled", `"Deeply thrilled"`],
    ["edited_on_ipad", "Edited on iPad"],
    ["edm", "EDM in Ad"],
    ["empty_wharf", "Shots on a Wharf"],
    ["esim_only_expanded", "eSIM Only Expanded"],
    ["exclusive_ai_features", "Exclusive AI Features"],
    ["faster_magsafe", "Faster Magsafe"],
    ["faster_wired", "Faster Wired Charging"],
    ["finewoven_discontinued", "FineWoven Discontinued"],
    ["free_space", "Free Space"],
    ["gonna_love_it", `"You're gonna love it"`],
    ["good_mornang", `"Good mornang!"`],
    ["here_it_is", `"And here it is"`],
    ["icloud_plus-1", "Bigger Free iCloud Storage"],
    ["icloud_plus", "New iCloud+ Plans"],
    ["improved_microphones", "Improved Microphones"],
    ["improved_performance", "Improved Performance"],
    ["improved_thermals", "Improved Thermals"],
    ["ipad_mini_7", "iPad Mini (7th Gen)"],
    ["iphone_se4", "iPhone SE (4th Gen)"],
    ["john_ternus", "John Ternus Wears Black"],
    ["larger_iphones", "Larger iPhones"],
    ["larger_watch", "Larger Apple Watch S10"],
    ["meaningless_graph", "Meaningless Graph"],
    ["movies_shot_on_iphone", "Movies Shot on iPhone"],
    ["new_ap", "AirPods (4th Gen)"],
    ["new_apm", "AirPods Max (2nd Gen)"],
    ["new_app", "AirPods Pro (3rd Gen)"],
    ["new_battery_design", "New Battery Design"],
    ["new_brown_color", "New Brown Color"],
    ["new_button", "Capture Button"],
    ["new_case_design", "New Case Design"],
    ["no_ultra_update", "No New Ultra"],
    ["pastel_watch_colors", "Pastel Watch Colors"],
    ["plastic_aw_se", "Plastic Apple Watch SE"],
    ["preorder_today", "Preorder Today"],
    ["privacy_mention", "Privacy Mention"],
    ["public_transit", "Public Transit Shot"],
    ["rainbow", "Rainbow Cameo"],
    ["raytracing", "Ray Tracing"],
    ["recycled_aluminum", "Recycled Aluminum"],
    ["shot_in_market", "Shot In Market"],
    ["shot_on_iphone", "Event Shot on iPhone"],
    ["sleep_apnea", "Sleep Apnea Detection"],
    ["slow_mo", "Slow-Mo Action Shots"],
    ["spatial_video", "Spatial Video on iPhone 16"],
    ["speed", "Superhuman Speed"],
    ["starting_at_just", `"Starting at just..."`],
    ["teleportation", "Teleportation"],
    ["thinner_aw", "Thinner Apple Watch"],
    ["transition", "Crazy Transitions"],
    ["ultra_thin_bezels", "Ultra Thin Bezels"],
    ["under_60", "Under 60 Minutes"],
    ["underground_lab", "Underground Lab"],
    ["upgraded_telephoto", "Upgraded Telephoto"],
    ["upgraded_ultrawide", "Upgraded Ultrawide"],
    ["usbc", "USB-C Accessories"],
    ["vertical_cameras", "Vertical Cameras"],
    ["vision_pro", "Vision Pro Mention"],
    ["vision_pro_countries", "AVP in More Countries"],
    ["weird_location", "Weird Location"],
    ["welcome", `"Welcome to Apple Park!"`],
    ["white_shoes", "Tim Wears White Shoes"],
    ["wifi6e", "WiFi 6e on base models"],
    ["wifi7", "WiFi 7"],
    ["woaw", `"Woaw!"`],
]);
