export const bingoItems = new Map([
    ["10_on_demos", "10+ Mins on Demos"],
    ["3nm", "3nm Process"],
    ["aaa_games", "AAA Games on Mac"],
    ["apple_park_night", "Apple Park at Night"],
    ["atv_segment", "Apple TV+ Segment"],
    ["deeply_thrilled", "\"Deeply Thrilled\""],
    ["free_space", "Free Space"],
    ["gaming_company", "Ft. Gaming Company"],
    ["gonna_love_it", "You're gonna love it"],
    ["imac_24", "Refreshed 24\" iMac"],
    ["imac_pro", "New iMac Pro"],
    ["ipad_air", "Refreshed iPad Air"],
    ["ipad_mini", "Refreshed iPad Mini"],
    ["ipad_pro", "Refreshed iPad Pros"],
    ["mac_gaming", "Mac Gaming Segment"],
    ["mac_sales", "Mac Sales Figures"],
    ["mac_testimonies", "New Mac Testimonies"],
    ["macbook_pro", "Refreshed MacBook Pros"],
    ["m3_chip", "M3 Chip"],
    ["m3_promax", "M3 Pro and Max Chips"],
    ["mba_13", "Refreshed 13\" Macbook Air"],
    ["mba_15", "Refreshed 15\" Macbook Air"],
    ["mbp_13", "13\" MBP Discontinued"],
    ["meaningless_graph", "Meaningless Graph"],
    ["new_apm", "AirPods Max (2nd Gen)"],
    ["new_display", "New Display"],
    ["no_imac_colors", "No New iMac Colors"],
    ["raytracing_hardware", "Ray Tracing Hardware"],
    ["spooky", "Spooky"],
    ["sustainability", "Sustainability Segment"],
    ["third_party_demo", "Boring 3rd Party Demo"],
    ["transition", "Crazy Transition"],
    ["underground_lab", "Underground Lab"],
    ["under_60", "Under 60 Minutes"],
    ["usbc", "USB-C Accessories"],
    ["welcome", "\"Welcome to Apple Park!\""],
]);