export const bingoTiles: Map<string, string> = new Map([
    ["10_on_demos", "10+ Mins on Demos"],
    ["256_pro_storage", "256GB Pro Base Storage"],
    ["all_day_battery", '"All-Day Battery"'],
    ["apple_arcade", "Arcade Mention"],
    ["apple_park_night", "Apple Park at Night"],
    ["apple_watch_lives", "Apple Watch Saves Lives"],
    ["atv_segment", "Apple TV+ Segment"],
    ["aw_new_band", "New Band Mechanism"],
    ["aw_se3", "Apple Watch SE (3rd Gen)"],
    ["carbon_neutral", "Carbon Neutral"],
    ["craig_skits", "Craig Skits"],
    ["deeply_thrilled", `"Deeply thrilled"`],
    ["edm", "EDM in Ad"],
    ["exclusive_ai_features", "Exclusive AI Features"],
    ["faster_magsafe", "Faster Magsafe"],
    ["free_space", "Free Space"],
    ["gonna_love_it", `"You're gonna love it"`],
    ["good_mornang", `"Good mornang!"`],
    ["here_it_is", `"And here it is"`],
    ["ipad_mini_7", "iPad Mini (7th Gen)"],
    ["iphone_se4", "iPhone SE (4th Gen)"],
    ["john_ternus", "John Ternus Wears Black"],
    ["larger_iphones", "Larger iPhones"],
    ["larger_watch", "Larger Apple Watch S10"],
    ["meaningless_graph", "Meaningless Graph"],
    ["new_ap", "AirPods (4th Gen)"],
    ["new_apm", "AirPods Max (2nd Gen)"],
    ["new_app", "AirPods Pro (3rd Gen)"],
    ["new_brown_color", "New Brown Color"],
    ["new_button", "New Button"],
    ["plastic_aw_se", "Plastic Apple Watch SE"],
    ["preorder_today", "Preorder Today"],
    ["privacy_mention", "Privacy Mention"],
    ["rainbow", "Rainbow Cameo"],
    ["raytracing", "Ray Tracing"],
    ["recycled_aluminum", "Recycled Aluminum"],
    ["speed", "Superhuman Speed"],
    ["starting_at_just", `"Starting at just..."`],
    ["teleportation", "Teleportation"],
    ["thinner_aw", "Thinner Apple Watch"],
    ["transition", "Crazy Transitions"],
    ["ultra_thin_bezels", "Ultra Thin Bezels"],
    ["under_60", "Under 60 Minutes"],
    ["underground_lab", "Underground Lab"],
    ["upgraded_telephoto", "Upgraded Telephoto"],
    ["upgraded_ultrawide", "Upgraded Ultrawide"],
    ["usbc", "USB-C Accessories"],
    ["vertical_cameras", "Vertical Cameras"],
    ["vision_pro", "Vision Pro Mention"],
    ["vision_pro_countries", "AVP in More Countries"],
    ["weird_location", "Weird Location"],
    ["welcome", `"Welcome to Apple Park!"`],
    ["white_shoes", "Tim Wears White Shoes"],
    ["wifi7", "WiFi 7"],
    ["woaw", `"Woaw!"`],
]);
