export const bingoTiles: Map<string, string> = new Map([
    ["10_on_demos", "10+ Mins on Demos"],
    ["128gb_air", "128GB iPad Air"],
    ["all_day_battery", '"All-Day Battery"'],
    ["apple_arcade", "Arcade Mention"],
    ["apple_pencil", "Apple Pencil Mention"],
    ["artists_ipad", "Artists Using iPad"],
    ["atv_segment", "Apple TV+ Segment"],
    ["carbon_neutral", "Carbon Neutral"],
    ["craig_skits", "Craig Skits"],
    ["deeply_thrilled", '"Deeply Thrilled"'],
    ["edm", "EDM in Ad"],
    ["exclusive_features", "Exclusive Features"],
    ["fastest_ipads", '"Our fastest iPads yet"'],
    ["free_space", "Free Space"],
    ["gaming_company", "Feat. Gaming Company"],
    ["gonna_love_it", '"You\'re gonna love it"'],
    ["good_mornang", '"Good mornang!"'],
    ["here_it_is", '"And here it is"'],
    ["improved_webcam", "Improved Webcam"],
    ["ipad_air", "Refreshed iPad Air"],
    ["ipad_color", "New iPad Color"],
    ["ipad_gaming", "iPad Gaming Segment"],
    ["ipad_mini", "Refreshed iPad mini"],
    ["ipad_pro", "Refreshed iPad Pros"],
    ["ipad_sales", "iPad Sales Figures"],
    ["ipad_testimonies", "New iPad Testimonies"],
    ["iphone_mention", "iPhone Mention"],
    ["m3_pro_ipad", "M3 Pro iPad"],
    ["magic_keyboard", "New Magic Keyboard"],
    ["max_memory", "Max Memory Increase"],
    ["meaningless_graph", "Meaningless Graph"],
    ["new_apm", "AirPods Max (2nd Gen)"],
    ["new_camera", "Upgraded Cameras"],
    ["oled", "OLED iPad Display"],
    ["pencil_discontinued", "AI Mention"],
    ["preorder_today", "Preorder Today"],
    ["privacy_mention", "Privacy Mention"],
    ["proraw", "ProRAW Mention"],
    ["rainbow", "Rainbow Cameo"],
    ["raytracing_hardware", "Ray Tracing Hardware"],
    ["recycled_aluminum", "Recycled Aluminum"],
    ["speed", "Superhuman Speed"],
    ["starting_at_just", '"Starting at just..."'],
    ["teleportation", "Teleportation"],
    ["third_party_demo", "Boring 3rd Party Demo"],
    ["transition", "Crazy Transitions"],
    ["under_60", "Under 60 Minutes"],
    ["underground_lab", "Underground Lab"],
    ["usbc", "USB-C Accessories"],
    ["vision_pro", "Vision Pro Segment"],
    ["weird_location", "Weird Location"],
    ["welcome", '"Welcome to Apple Park!"'],
    ["white_shoes", "Tim Wears White Shoes"],
    ["woaw", '"Woaw!"'],
]);
