export const bingoItems: Map<string, string> = new Map([
    ["3nm", "3nm Process"],
    ["10_on_demos", "10+ Mins on Demos"],
    ["aaa_games", "AAA Games on Mac"],
    ["all_day_battery", '"All-Day Battery"'],
    ["apple_arcade", "Arcade Mention"],
    ["apple_park_night", "Apple Park at Night"],
    ["apple_pencil", "Apple Pencil Mention"],
    ["artists_mac", "Artists Using Mac"],
    ["atv_segment", "Apple TV+ Segment"],
    ["carbon_neutral", "Carbon Neutral"],
    ["costume", "Halloween Costume"],
    ["craig_skits", "Craig Skits"],
    ["deeply_thrilled", '"Deeply Thrilled"'],
    ["edm", "EDM in Ad"],
    ["fastest_macs", '"Our fastest Macs yet"'],
    ["free_space", "Free Space"],
    ["gaming_company", "Feat. Gaming Company"],
    ["gonna_love_it", '"You\'re gonna love it"'],
    ["good_evening", '"Good evening!"'],
    ["here_it_is", '"And here it is"'],
    ["imac_24", 'Refreshed 24" iMac'],
    ["imac_pro", "New iMac Pro"],
    ["improved_webcam", "Improved Webcam"],
    ["ipad_air", "Refreshed iPad Air"],
    ["ipad_mini", "Refreshed iPad mini"],
    ["ipad_pro", "Refreshed iPad Pros"],
    ["iphone_mention", "iPhone 15 Mention"],
    ["john_ternus", "John Ternus Wears Black"],
    ["m3_chip", "M3 Chip"],
    ["m3_promax", "M3 Pro and Max Chips"],
    ["mac_gaming", "Mac Gaming Segment"],
    ["mac_sales", "Mac Sales Figures"],
    ["mac_testimonies", "New Mac Testimonies"],
    ["macbook_pro", "Refreshed MacBook Pros"],
    ["max_memory", "Max Memory Increase"],
    ["mba_13", 'Refreshed 13" Macbook Air'],
    ["mba_15", 'Refreshed 15" Macbook Air'],
    ["mbp_13", '13" MBP Discontinued'],
    ["mbp_color", "New MBP Color"],
    ["meaningless_graph", "Meaningless Graph"],
    ["new_apm", "AirPods Max (2nd Gen)"],
    ["new_display", "New Display"],
    ["no_imac_colors", "No New iMac Colors"],
    ["preorder_today", "Preorder Today"],
    ["price_decrease", "Mac Price Decrease"],
    ["privacy_mention", "Privacy Mention"],
    ["proraw", "ProRAW Mention"],
    ["rainbow", "Rainbow Cameo"],
    ["raytracing_hardware", "Ray Tracing Hardware"],
    ["recycled_aluminum", "Recycled Aluminum"],
    ["speed", "Superhuman Speed"],
    ["spooky", "Spooky"],
    ["starting_at_just", '"Starting at just..."'],
    ["teleportation", "Teleportation"],
    ["third_party_demo", "Boring 3rd Party Demo"],
    ["transition", "Crazy Transitions"],
    ["under_60", "Under 60 Minutes"],
    ["underground_lab", "Underground Lab"],
    ["usbc", "USB-C Accessories"],
    ["vision_pro", "Vision Pro Segment"],
    ["weird_location", "Weird Location"],
    ["welcome", '"Welcome to Apple Park!"'],
    ["white_shoes", "Tim Wears White Shoes"],
    ["woaw", '"Woaw!"'],
]);
